#/** * @author MayilaiMuthu * @apiNote 21-03-2023 **/

#Data Source Config
#disabled job run at startup   
spring:
   batch:
       jdbc:
          initialize-schema: ALWAYS
       job:
         enabled: false
   datasource:
       driver-class-name: com.mysql.cj.jdbc.Driver
       url: jdbc:mysql://localhost/springbatch
       username: root
       password: root
       
#Console Config

#spring.batch.initialize-schema=ALWAYS

#   h2:
#    console:
#      enabled: true  
       
#JPA Config

   jpa:
      show-sql: true
      hibernate:
         ddl-auto: create
      properties:
         hibernate:
             dialect: org.hibernate.dialect.MySQL5Dialect
             
#Server Config             

server:
    port: 7074
    servlet:
      context-path: /api

  